let EMPLOYEES = [
  {
    id: crypto.randomUUID(),
    firstName: 'Alice',
    lastName: 'Johnson',
    dateOfEmployment: '2020-05-15',
    dateOfBirth: '1992-03-12',
    phone: '+1 555-0123',
    email: 'alice.johnson@company.com',
    department: 'Analytics',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Bob',
    lastName: 'Smith',
    dateOfEmployment: '2019-11-23',
    dateOfBirth: '1987-07-08',
    phone: '+1 555-0456',
    email: 'bob.smith@company.com',
    department: 'Tech',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Carol',
    lastName: 'Nguyen',
    dateOfEmployment: '2021-04-01',
    dateOfBirth: '1995-09-30',
    phone: '+1 555-0789',
    email: 'carol.nguyen@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'David',
    lastName: 'Lee',
    dateOfEmployment: '2018-06-12',
    dateOfBirth: '1985-01-25',
    phone: '+1 555-1010',
    email: 'david.lee@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Eva',
    lastName: 'Martinez',
    dateOfEmployment: '2022-02-20',
    dateOfBirth: '1996-12-05',
    phone: '+1 555-1122',
    email: 'eva.martinez@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Frank',
    lastName: 'O’Connor',
    dateOfEmployment: '2020-10-10',
    dateOfBirth: '1990-10-10',
    phone: '+1 555-1333',
    email: 'frank.oconnor@company.com',
    department: 'Tech',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Grace',
    lastName: 'Kim',
    dateOfEmployment: '2023-01-15',
    dateOfBirth: '1997-02-18',
    phone: '+1 555-1444',
    email: 'grace.kim@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Henry',
    lastName: 'Turner',
    dateOfEmployment: '2017-03-09',
    dateOfBirth: '1984-08-14',
    phone: '+1 555-1555',
    email: 'henry.turner@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Isabel',
    lastName: 'Davis',
    dateOfEmployment: '2021-09-28',
    dateOfBirth: '1991-04-03',
    phone: '+1 555-1666',
    email: 'isabel.davis@company.com',
    department: 'Analytics',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Jack',
    lastName: 'White',
    dateOfEmployment: '2016-12-01',
    dateOfBirth: '1983-06-21',
    phone: '+1 555-1777',
    email: 'jack.white@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Alice',
    lastName: 'Johnson',
    dateOfEmployment: '2020-05-15',
    dateOfBirth: '1992-03-12',
    phone: '+1 555-0123',
    email: 'alice.johnson@company.com',
    department: 'Analytics',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Bob',
    lastName: 'Smith',
    dateOfEmployment: '2019-11-23',
    dateOfBirth: '1987-07-08',
    phone: '+1 555-0456',
    email: 'bob.smith@company.com',
    department: 'Tech',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Carol',
    lastName: 'Nguyen',
    dateOfEmployment: '2021-04-01',
    dateOfBirth: '1995-09-30',
    phone: '+1 555-0789',
    email: 'carol.nguyen@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'David',
    lastName: 'Lee',
    dateOfEmployment: '2018-06-12',
    dateOfBirth: '1985-01-25',
    phone: '+1 555-1010',
    email: 'david.lee@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Eva',
    lastName: 'Martinez',
    dateOfEmployment: '2022-02-20',
    dateOfBirth: '1996-12-05',
    phone: '+1 555-1122',
    email: 'eva.martinez@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Frank',
    lastName: 'O’Connor',
    dateOfEmployment: '2020-10-10',
    dateOfBirth: '1990-10-10',
    phone: '+1 555-1333',
    email: 'frank.oconnor@company.com',
    department: 'Tech',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Grace',
    lastName: 'Kim',
    dateOfEmployment: '2023-01-15',
    dateOfBirth: '1997-02-18',
    phone: '+1 555-1444',
    email: 'grace.kim@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Henry',
    lastName: 'Turner',
    dateOfEmployment: '2017-03-09',
    dateOfBirth: '1984-08-14',
    phone: '+1 555-1555',
    email: 'henry.turner@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Isabel',
    lastName: 'Davis',
    dateOfEmployment: '2021-09-28',
    dateOfBirth: '1991-04-03',
    phone: '+1 555-1666',
    email: 'isabel.davis@company.com',
    department: 'Analytics',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Jack',
    lastName: 'White',
    dateOfEmployment: '2016-12-01',
    dateOfBirth: '1983-06-21',
    phone: '+1 555-1777',
    email: 'jack.white@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Alice',
    lastName: 'Johnson',
    dateOfEmployment: '2020-05-15',
    dateOfBirth: '1992-03-12',
    phone: '+1 555-0123',
    email: 'alice.johnson@company.com',
    department: 'Analytics',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Bob',
    lastName: 'Smith',
    dateOfEmployment: '2019-11-23',
    dateOfBirth: '1987-07-08',
    phone: '+1 555-0456',
    email: 'bob.smith@company.com',
    department: 'Tech',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Carol',
    lastName: 'Nguyen',
    dateOfEmployment: '2021-04-01',
    dateOfBirth: '1995-09-30',
    phone: '+1 555-0789',
    email: 'carol.nguyen@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'David',
    lastName: 'Lee',
    dateOfEmployment: '2018-06-12',
    dateOfBirth: '1985-01-25',
    phone: '+1 555-1010',
    email: 'david.lee@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Eva',
    lastName: 'Martinez',
    dateOfEmployment: '2022-02-20',
    dateOfBirth: '1996-12-05',
    phone: '+1 555-1122',
    email: 'eva.martinez@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Frank',
    lastName: 'O’Connor',
    dateOfEmployment: '2020-10-10',
    dateOfBirth: '1990-10-10',
    phone: '+1 555-1333',
    email: 'frank.oconnor@company.com',
    department: 'Tech',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Grace',
    lastName: 'Kim',
    dateOfEmployment: '2023-01-15',
    dateOfBirth: '1997-02-18',
    phone: '+1 555-1444',
    email: 'grace.kim@company.com',
    department: 'Analytics',
    position: 'Junior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Henry',
    lastName: 'Turner',
    dateOfEmployment: '2017-03-09',
    dateOfBirth: '1984-08-14',
    phone: '+1 555-1555',
    email: 'henry.turner@company.com',
    department: 'Tech',
    position: 'Senior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Isabel',
    lastName: 'Davis',
    dateOfEmployment: '2021-09-28',
    dateOfBirth: '1991-04-03',
    phone: '+1 555-1666',
    email: 'isabel.davis@company.com',
    department: 'Analytics',
    position: 'Medior',
  },
  {
    id: crypto.randomUUID(),
    firstName: 'Jack',
    lastName: 'White',
    dateOfEmployment: '2016-12-01',
    dateOfBirth: '1983-06-21',
    phone: '+1 555-1777',
    email: 'jack.white@company.com',
    department: 'Tech',
    position: 'Senior',
  },
];

export const fetchEmployees = () =>
  new Promise((res) => setTimeout(() => res([...EMPLOYEES]), 400));

export const addEmployeeApi = (employee) =>
  new Promise((res) => {
    setTimeout(() => {
      const newEmp = {id: crypto.randomUUID(), ...employee};
      EMPLOYEES.push(newEmp);
      res(newEmp);
    }, 400);
  });

export const updateEmployeeApi = (id, changes) =>
  new Promise((res) => {
    setTimeout(() => {
      EMPLOYEES = EMPLOYEES.map((e) => (e.id === id ? {...e, ...changes} : e));
      res(EMPLOYEES.find((e) => e.id === id));
    }, 400);
  });

export const deleteEmployeeApi = (id) =>
  new Promise((res) => {
    setTimeout(() => {
      EMPLOYEES = EMPLOYEES.filter((e) => e.id !== id);
      res(id);
    }, 400);
  });
